// TODO: add at least 2 explorers per coin

const explorerList = {
  SAFE: 'https://explorer.safecoin.org',
  KV: 'http://kv.explorer.fairexchange.org',
  OOT: 'http://explorer.utrum.io',
  MSHARK: 'http://MSHARK.explorer.fairexchange.org',
  REVS: 'http://revs.explorer.fairexchange.org',
  SUPERNET: 'http://SUPERNET.explorer.fairexchange.org',
  DEX: 'http://DEX.explorer.fairexchange.org',
  PANGEA: 'http://PANGEA.explorer.fairexchange.org',
  JUMBLR: 'http://JUMBLR.explorer.fairexchange.org',
  BET: 'http://BET.explorer.fairexchange.org',
  CRYPTO: 'http://CRYPTO.explorer.fairexchange.org',
  HODL: 'http://HODL.explorer.fairexchange.org',
  SHARK: 'http://SHARK.explorer.fairexchange.org',
  BOTS: 'http://BOTS.explorer.fairexchange.org',
  MGW: 'http://MGW.explorer.fairexchange.org',
  WLC: 'http://WIRELESS.explorer.fairexchange.org',
  CHIPS: 'http://CHIPS1.explorer.fairexchange.org',
  COQUI: 'https://explorer.coqui.cash',
  CHAIN: 'https://explorer.chainmakers.co',
  GLXT: 'http://glx.info',
  BNTN: 'http://chain.blocnation.io',
  EQL: 'http://178.62.240.191',
  MNZ: 'https://www.mnzexplorer.com',
  BTCH: 'http://www.btch.host',
  BTC: 'https://blockchain.info',
  HUSH: 'https://explorer.myhush.org',
  PIZZA: 'http://pizza.safecoinchainz.info',
  BEER: 'http://beer.safecoinchainz.info',
  NINJA: 'https://explorer.fund.ninja',
  VOTE2018: 'http://88.99.226.252',
  QTUM: 'https://explorer.qtum.org',
  DNR: 'http://denarius.name',
  LTC: 'https://live.blockcypher.com/ltc',
  DOGE: 'https://live.blockcypher.com/doge',
  DASH: 'https://live.blockcypher.com/dash',
  MONA: 'https://bchain.info/MONA',
  VIA: 'https://explorer.viacoin.org',
  VTC: 'http://explorer.vertcoin.info',
  NMC: 'https://namecha.in',
  DGB: 'https://digiexplorer.info',
  CRW: 'http://ex.crownlab.eu',
  ABY: 'http://explorer.artbyte.me',
  GAME: 'https://blockexplorer.gamecredits.com/transactions/',
  MAC: 'http://explorer.machinecoin.org',
  IOP: 'http://mainnet.iop.cash',
  BTG: 'https://btgexplorer.com',
  BCH: 'https://bitcoincash.blockexplorer.com',
  ZCL: 'http://explorer.zclmine.pro',
  SNG: 'https://explorer.snowgem.org/',
  ZMY: 'https://myriadexplorer.com',
  BTX: 'http://explorer.bitcore.cc',
  BTCZ: 'https://explorer.bitcoinz.site',
  HODLC: 'http://www.fuzzbawls.pw/explore/HOdlcoin/tx.php?tx=',
  SIB: 'https://chain.sibcoin.net/en/tx/',
  ZEC: 'https://explorer.zcha.in/transactions/',
  BLK: 'https://explorer.coinpayments.net/transaction.php?chain=4&hash=',
  ARG: 'https://prohashing.com/explorer/Argentum/',
  FAIR: 'https://chain.fair.to/transaction?transaction=',
};

export default explorerList;